name: Larastan Code Analysis

on:
  push:
    branches: [ "master" ]

jobs:
  larastan-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run Larastan
      run: ./vendor/bin/phpstan analyse
